server:
  port: 8082
hm:
  db:
    database: hm-cart
  swagger:
    title: "CSIMS购物车管理接口文档"
    package: com.zjn.cart.controller
    description: "CSIMS购物车管理接口文档"
feign:
#  sentinel:
#    enabled: true # 开启feign接口的流量控制
  okhttp:
    enabled: true
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090 # sentinel控制台地址
      http-method-specify: true # 将请求方式作为资源名称，防止RestFul风格下的簇点重复
seata:
  data-source-proxy-mode: AT
  tx-service-group: default_tx_group # 事务组名称
  service:
    vgroup-mapping: # 事务组与tc集群的映射关系
      default_tx_group: default