server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 192.168.121.128:8848
    gateway:
      routes:
        - id: item-service
          uri:
            lb://item-service
          predicates:
            - Path=/items/**,/search/**
        - id: cart-service
          uri:
            lb://carts-service
          predicates:
            - Path=/carts/**
        - id: user-service
          uri:
            lb://user-service
          predicates:
            - Path=/addresses/**,/users/**
        - id: pay-service
          uri:
            lb://pay-service
          predicates:
            - Path=/pay-orders/**
        - id: trade-service
          uri:
            lb://trade-service
          predicates:
            - Path=/orders/**